[package]
name = "gui"
version = "0.1.0"
edition = "2021"
default-run = "gui"

[dependencies]
ntscrs = { path = "../ntscrs" }
eframe = { version = "0.22.0", features=["persistence"] }
env_logger = "0.10"
image = "0.24.7"
rfd = "0.11.4"
snafu = "0.7.5"